[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pipeline"
version = "0.1.0"
description = "GitHub events ETL with Pandas"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2",
]

[tool.setuptools.packages.find]
where = ["src"]

